import { Link } from 'react-router-dom'
import SiteLayout from '../layouts/SiteLayout.jsx'
import { usePageMeta } from '../hooks/usePageMeta.js'

const TITLE = 'Terms of Service'
const DESCRIPTION =
  'The terms that govern your use of Commercial Solar Calculator: informational-use-only scope, no warranty, limitation of liability, and third-party advertising.'
const PATH = '/terms-of-service'
const LAST_UPDATED = 'July 10, 2026'

function TermsPage() {
  usePageMeta({
    title: `${TITLE} | Commercial Solar Calculator`,
    description: DESCRIPTION,
    path: PATH,
  })

  return (
    <SiteLayout
      title={TITLE}
      description="The terms that govern your use of this site and its calculators."
      breadcrumbLabel={TITLE}
    >
      <div className="mx-auto max-w-3xl">
        <section className="animate-fade-in-up rounded-2xl bg-white p-6 shadow-lg ring-1 ring-slate-900/5 dark:bg-slate-800 dark:ring-white/10 sm:p-10">
          <p className="text-xs font-medium uppercase tracking-wide text-slate-400 dark:text-slate-500">
            Last updated: {LAST_UPDATED}
          </p>

          <div className="prose-legal mt-4 space-y-6 text-sm leading-relaxed text-slate-600 dark:text-slate-300">
            <p>
              By accessing or using Commercial Solar Calculator (&quot;the Tool&quot;), you agree
              to the following terms.
            </p>
            <ul className="list-disc space-y-3 pl-5">
              <li>
                <strong className="text-slate-900 dark:text-white">Informational use only:</strong>{' '}
                outputs are simplified, formula-based estimates and do not constitute financial,
                tax, engineering, or legal advice.
              </li>
              <li>
                <strong className="text-slate-900 dark:text-white">No warranty:</strong> the Tool
                is provided &quot;as is&quot; without warranties of any kind, express or implied,
                including as to accuracy, completeness, or fitness for a particular purpose.
              </li>
              <li>
                <strong className="text-slate-900 dark:text-white">Limitation of liability:</strong>{' '}
                to the maximum extent permitted by law, we are not liable for any damages arising
                from reliance on results generated by the Tool.
              </li>
              <li>
                <strong className="text-slate-900 dark:text-white">Third-party advertising:</strong>{' '}
                this site may display third-party advertising; we are not responsible for the
                content, offers, or practices of third-party advertisers.
              </li>
              <li>
                <strong className="text-slate-900 dark:text-white">Changes:</strong> we may update
                these Terms or the Tool at any time without prior notice.
              </li>
            </ul>
            <p>
              Questions about these Terms can be sent via our{' '}
              <Link to="/contact" className="font-semibold text-emerald-600 hover:underline">
                Contact Form
              </Link>
              .
            </p>
          </div>
        </section>
      </div>
    </SiteLayout>
  )
}

export default TermsPage
