import { useState } from 'react'
import { Link } from 'react-router-dom'
import Modal from './Modal.jsx'
import { CALCULATOR_PAGES } from '../data/calculatorPages.js'

// Rendered as buttons that open an in-page modal.
const MODAL_FOOTER_LINKS = [
  { id: 'methodology', label: 'Calculation Methodology' },
  { id: 'terms', label: 'Terms of Service' },
]

// Rendered as real links to their own standalone, indexable pages.
const PAGE_FOOTER_LINKS = [
  { path: '/privacy-policy', label: 'Privacy Policy' },
  { path: '/cookie-policy', label: 'Cookie Policy' },
]

function MethodologyContent() {
  return (
    <>
      <p>
        This calculator uses simplified, formula-based estimates so results update instantly as
        you adjust the sliders. It is not a substitute for a site-specific engineering or tax
        proposal.
      </p>
      <ul className="list-disc space-y-2 pl-5">
        <li>
          <strong>System Size:</strong> your monthly bill is converted to estimated monthly kWh
          usage at a blended $0.13/kWh national average commercial rate, then sized against
          roughly 135 kWh of monthly production per installed kW at 120% of that usage to allow
          for future load growth.
        </li>
        <li>
          <strong>Gross System Cost:</strong> System Size × $2,300 per kW, a blended national
          average for commercial turnkey installation.
        </li>
        <li>
          <strong>Federal ITC:</strong> 30% of Gross System Cost under IRC Section 48E.
        </li>
        <li>
          <strong>Depreciable Basis:</strong> Gross System Cost minus 50% of the ITC amount, per
          the basis-reduction rule in IRC Section 50(c).
        </li>
        <li>
          <strong>MACRS Tax Shield:</strong> Depreciable Basis × (21% federal + your state
          corporate tax rate) — a blended estimate of the 5-year accelerated depreciation
          benefit.
        </li>
        <li>
          <strong>Net Capital Required:</strong> Gross System Cost minus the ITC minus the MACRS
          Tax Shield.
        </li>
        <li>
          <strong>Payback Period:</strong> Net Capital Required ÷ (Monthly Bill × 12 × 95%
          offset).
        </li>
        <li>
          <strong>25-Year Cash Flow:</strong> annual savings compounding at 3% per year, starting
          from a negative position equal to Net Capital Required.
        </li>
      </ul>
    </>
  )
}

function TermsContent() {
  return (
    <>
      <p>
        By accessing or using the Commercial Solar Calculator (&quot;the Tool&quot;), you agree
        to the following terms.
      </p>
      <ul className="list-disc space-y-2 pl-5">
        <li>
          <strong>Informational use only:</strong> outputs are simplified, formula-based
          estimates and do not constitute financial, tax, engineering, or legal advice.
        </li>
        <li>
          <strong>No warranty:</strong> the Tool is provided &quot;as is&quot; without warranties
          of any kind, express or implied, including as to accuracy, completeness, or fitness for
          a particular purpose.
        </li>
        <li>
          <strong>Limitation of liability:</strong> to the maximum extent permitted by law, we
          are not liable for any damages arising from reliance on results generated by the Tool.
        </li>
        <li>
          <strong>Third-party advertising:</strong> this site may display third-party
          advertising; we are not responsible for the content, offers, or practices of
          third-party advertisers.
        </li>
        <li>
          <strong>Changes:</strong> we may update these Terms or the Tool at any time without
          prior notice.
        </li>
      </ul>
    </>
  )
}

const MODAL_CONTENT = {
  methodology: { title: 'Calculation Methodology', body: <MethodologyContent /> },
  terms: { title: 'Terms of Service', body: <TermsContent /> },
}

function Footer() {
  const [activeModal, setActiveModal] = useState(null)

  return (
    <footer className="mt-12 border-t border-slate-800 bg-slate-900 py-8 text-slate-400">
      <div className="mx-auto max-w-5xl px-4">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-300">
          Free Commercial Solar Calculators
        </h2>
        <nav aria-label="All calculators" className="mt-4 grid grid-cols-2 gap-x-6 gap-y-2 sm:grid-cols-3">
          {CALCULATOR_PAGES.map((page) => (
            <Link
              key={page.path}
              to={page.path}
              className="text-xs text-slate-400 transition hover:text-emerald-400"
            >
              {page.label}
            </Link>
          ))}
        </nav>

        <h2 className="mt-8 border-t border-slate-800 pt-6 text-sm font-semibold uppercase tracking-wide text-slate-300">
          Legal &amp; Tax Disclaimer
        </h2>
        <p className="mt-3 text-xs leading-relaxed">
          This calculator provides estimates for informational purposes only and does not
          constitute tax, legal, or financial advice. Figures referencing the Section 48E
          Investment Tax Credit (ITC) under the Internal Revenue Code are based on publicly
          available federal guidance and may vary based on project eligibility, prevailing wage
          and apprenticeship requirements, energy community adders, and other statutory
          conditions. Depreciation estimates assume a 5-year Modified Accelerated Cost Recovery
          System (MACRS) property classification and a reduced depreciable basis consistent with
          current ITC basis-reduction rules. Actual results depend on your organization's
          specific tax position, applicable state incentives, equipment pricing, and financing
          terms. Consult a qualified tax professional or licensed solar engineer before making
          investment decisions.
        </p>

        <nav
          aria-label="Site information"
          className="mt-6 flex flex-wrap gap-x-6 gap-y-2 border-t border-slate-800 pt-6 text-xs"
        >
          {MODAL_FOOTER_LINKS.map((link) => (
            <button
              key={link.id}
              type="button"
              onClick={() => setActiveModal(link.id)}
              className="font-medium text-slate-300 underline decoration-slate-600 underline-offset-4 transition hover:text-emerald-400 focus:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500/40"
            >
              {link.label}
            </button>
          ))}
          {PAGE_FOOTER_LINKS.map((link) => (
            <Link
              key={link.path}
              to={link.path}
              className="font-medium text-slate-300 underline decoration-slate-600 underline-offset-4 transition hover:text-emerald-400 focus:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500/40"
            >
              {link.label}
            </Link>
          ))}
        </nav>

        <p className="mt-4 text-xs text-slate-500">
          &copy; {new Date().getFullYear()} Commercial Solar Calculator. All rights reserved.
        </p>
      </div>

      {MODAL_FOOTER_LINKS.map((link) => (
        <Modal
          key={link.id}
          title={MODAL_CONTENT[link.id].title}
          isOpen={activeModal === link.id}
          onClose={() => setActiveModal(null)}
        >
          {MODAL_CONTENT[link.id].body}
        </Modal>
      ))}
    </footer>
  )
}

export default Footer
